"""
Utility functions for Lingua standalone app.

Migrated from Calibre plugin lib/utils.py.
Changes:
  - mechanize.Browser → httpx.Client
  - calibre.get_proxies → urllib.request.getproxies
  - Relative imports adjusted for lingua.core package
"""

import os
import re
import sys
import ssl
import socket
import hashlib
import traceback
from subprocess import Popen
from urllib.request import getproxies

import httpx

from .cssselect import GenericTranslator, SelectorError


ns = {'x': 'http://www.w3.org/1999/xhtml'}
is_test = 'unittest' in sys.modules


def dummy(*args, **kwargs):
    pass


def get_resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller."""
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        # Fallback to current directory for dev
        # For our package structure, lingua/core/utils.py is 2 levels deep from 'lingua' root
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    return os.path.join(base_path, relative_path)


def sep(char='═', count=38):
    return char * count


def css(selector):
    try:
        return GenericTranslator().css_to_xpath(selector, prefix='self::x:')
    except SelectorError:
        return None


def css_to_xpath(selectors):
    patterns = []
    for selector in selectors:
        if rule := css(selector):
            patterns.append(rule)
    return patterns


def create_xpath(selectors):
    selectors = (selectors,) if isinstance(selectors, str) else selectors
    return './/*[%s]' % ' or '.join(css_to_xpath(selectors))


def uid(*args):
    md5 = hashlib.md5()
    for arg in args:
        md5.update(arg if isinstance(arg, bytes) else arg.encode('utf-8'))
    return md5.hexdigest()


def trim(text):
    # Replace \xa0 with whitespace to be compatible with Python 2.x.
    text = re.sub(u'\u00a0|\u3000', ' ', text)
    # Remove the \x07 from the translation generated by some engine.
    text = re.sub(u'\u200b|\ufeff', '', text)
    # Combine multiple white spaces into a single space.
    text = re.sub(r'\s+', ' ', text)
    # Remove all potential non-printable characters.
    text = re.sub(r'(?![\n\r\t])[\x00-\x1f\x7f-\xa0\xad]', '', text)
    return text.strip()


def chunk(items, length=0):
    if length < 1:
        for item in items:
            yield [item]
        return
    item_length = len(items)
    length = item_length if length > item_length else length
    chunk_size = item_length / length
    for i in range(length):
        yield items[int(chunk_size*i):int(chunk_size*(i+1))]


def group(numbers):
    ranges = []
    current_range: list[int] = []
    numbers = sorted(numbers)
    for number in numbers:
        if not current_range:
            current_range = [number, number]
        elif number - current_range[-1] == 1:
            current_range[-1] = number
        else:
            ranges.append(tuple(current_range))
            current_range = [number, number]
    ranges.append(tuple(current_range))
    return ranges


def sorted_mixed_keys(s):
    # https://docs.python.org/3/reference/expressions.html#value-comparisons
    return [int(s) if s.isdigit() else s for s in re.split(r'(\d+)', s)]


def is_str(data):
    return type(data).__name__ in ('str', 'unicode')


def is_proxy_available(host, port, timeout=1):
    try:
        host = host.replace('http://', '')
        socket.create_connection((host, int(port)), timeout).close()
    except Exception:
        return False
    return True


def size_by_unit(number, unit='KB'):
    unit = unit.upper()
    multiple = {'KB': 1, 'MB': 2}
    if unit not in multiple:
        unit = 'KB'
    return round(float(number) / (1000 ** multiple[unit]), 2)


def open_path(path):
    if sys.platform.startswith('win32'):
        try:
            os.startfile(path)
        except Exception:
            Popen(['explorer', path])
    elif sys.platform.startswith('darwin'):
        Popen(['open', path])
    else:
        Popen(['xdg-open', path])


def open_file(path, encoding='utf-8'):
    with open(path, 'r', encoding=encoding, newline=None) as file:
        return file.read()


def traceback_error():
    return traceback.format_exc(chain=False).strip()


def request(
        url, data=None, headers={}, method='GET', timeout=30, proxy_uri=None,
        raw_object=False) -> httpx.Response | str:
    """
    HTTP request function using httpx (replaces mechanize.Browser).

    When raw_object=True, returns the httpx.Response directly (for streaming).
    When raw_object=False (default), returns decoded response text.
    """
    # Build proxy config
    proxy = None
    if proxy_uri is not None:
        proxy = proxy_uri if proxy_uri.startswith('http') else f'http://{proxy_uri}'
    else:
        system_proxies = getproxies()
        proxy = system_proxies.get('https') or system_proxies.get('http')

    # Build client with SSL verification disabled (matches original behavior)
    client = httpx.Client(
        verify=False,
        proxy=proxy,
        timeout=timeout,
        follow_redirects=True,
    )

    # Determine how to pass data to httpx
    req_kwargs = {
        'method': method,
        'url': url,
        'headers': headers,
    }
    
    if data is not None:
        if isinstance(data, dict):
            if method.upper() == 'GET':
                req_kwargs['params'] = data
            else:
                # Default to form data for dicts (urllib/mechanize behavior)
                req_kwargs['data'] = data
        elif isinstance(data, str):
            req_kwargs['content'] = data.encode('utf-8')
        else:
            req_kwargs['content'] = data

    if raw_object:
        # Caller MUST use this as a context manager: 'with request(...) as resp:'
        # This keeps the client and connection open.
        return client.stream(**req_kwargs)

    with client:
        response = client.request(**req_kwargs)
        response.raise_for_status()
        return response.text.strip()
